apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
   access: proxy
    url: http://192.168.50.22:8086
    secureJsonData:
      token: gSZEdyHruvK7SkyTzbzkX3c1fzQ5Nm0z9ZN-RJgIJ5d2aPCe93YEQ1wvg3agdEJDTTzp9kTj53mTR_t5cFXA-w==
    jsonData:
      version: Flux
      organization: hydromesh_org
      defaultBucket: hydromesh_db
      tlsSkipVerify: true
